run:
  # vendor means that when the golangci-lint tool runs it doesn't pull down the dependency repos
  # with the flag it assumes the vendor folder is in a good state and doesn't check dependencies
  # Alternative: set to readonly if you want the linter to fail if your go.mod file has an out of date dependency
  modules-download-mode: vendor
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - forcetypeassert
    - exhaustive
    - gofmt
    - whitespace
issues:
  exclude-rules:
    - linters:
        - errcheck
      text: ".*logger.Sync.*"